import Foundation
import Security

/// The per-request replay killer: 24 fresh bytes from SecRandomCopyBytes,
/// generated by the root verifier itself, never accepted from a caller.
public enum Nonce {
    public static let byteCount = 24

    public enum NonceError: Error, Sendable {
        case entropyUnavailable(OSStatus)
    }

    public static func generate() throws -> Data {
        var bytes = [UInt8](repeating: 0, count: byteCount)
        let status = SecRandomCopyBytes(kSecRandomDefault, byteCount, &bytes)
        guard status == errSecSuccess else {
            throw NonceError.entropyUnavailable(status)
        }
        return Data(bytes)
    }
}
