#!/bin/bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
version_file="$root/VERSION"
output="$root/Sources/CCSudo/Version.swift"
version="$(tr -d '\r\n' < "$version_file")"

semver='^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'
[[ "$version" =~ $semver ]] || {
    echo "invalid VERSION: $version" >&2
    exit 1
}

generated="$(mktemp)"
trap 'rm -f "$generated"' EXIT
printf '%s\n' \
    '// Generated by scripts/generate-version.sh from VERSION. Do not edit.' \
    '' \
    '/// The version stamped into every build. The brew-installed CLI passes it to' \
    '/// the root-owned verifier copy (`exec --client-version`), which hard-fails on' \
    '/// any mismatch with its own value — so a `brew upgrade` that outruns' \
    '/// `cc-sudo install` is a loud, routable error, never a silent skew.' \
    'public enum Version {' \
    "    public static let current = \"$version\"" \
    '}' > "$generated"

case "${1:-}" in
    "")
        cp "$generated" "$output"
        ;;
    --check)
        if ! cmp -s "$generated" "$output"; then
            diff -u "$output" "$generated" >&2 || true
            echo "Sources/CCSudo/Version.swift is stale; run scripts/generate-version.sh" >&2
            exit 1
        fi
        ;;
    *)
        echo "usage: $0 [--check]" >&2
        exit 2
        ;;
esac
