name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    uses: yasyf/homebrew-tap/.github/workflows/release-swift.yml@c9d8821d874a9d5c7c322b6f3ee0aa1c642e3bc4
    secrets: inherit
